name: "haiku-ci"
on: [push, pull_request]

jobs:
  build-haiku:
    timeout-minutes: 60
    runs-on: ${{ matrix.config.runner }}
    name: build-${{ matrix.config.os }}-${{ matrix.config.version }}-${{ matrix.config.architecture }}

    strategy:
      fail-fast: false
      matrix:
        config:
          # The OS versions supported are specific to the version of the action
          # https://github.com/cross-platform-actions/action/blob/master/changelog.md
          - { os: haiku, version: 'r1beta5', runner: 'ubuntu-latest', architecture: 'x86-64' }
          - { os: haiku, version: 'r1beta5',  runner: 'ubuntu-latest', architecture: 'x86' }
          - { os: haiku, version: 'nightly', runner: 'ubuntu-latest', architecture: 'x86-64' }
          - { os: haiku, version: 'nightly',  runner: 'ubuntu-latest', architecture: 'x86' }

    steps:
      - uses: actions/checkout@v4

      - uses: korli/action@v0.25.0-haiku3
        with:
          operating_system: ${{ matrix.config.os }}
          version: ${{ matrix.config.version }}
          architecture: ${{ matrix.config.architecture }}
          run: |
            if [[ `uname -m` == BePC ]]; then
              ssh user@localhost "pkgman update -y haiku_x86_devel devel:libdjvulibre_x86 devel:libfreetype_x86 devel:libjbig2dec_x86 devel:libjpeg_x86 devel:libmupdf_x86 devel:libopenjp2_x86	devel:libz_x86 cmd:gcc_x86 gcc_x86_syslibs_devel cmd:as_x86" &&
              cd application && setarch x86 make
            else
              ssh user@localhost "pkgman update -y haiku_devel devel:libdjvulibre devel:libfreetype devel:libjbig2dec devel:libjpeg devel:libmupdf devel:libopenjp2	devel:libz cmd:gcc gcc_syslibs_devel cmd:as" &&
              cd application && make
            fi
